// @fragiola/data-grid: the framework-free core of the headless data grid.

export type { Axis, Size } from "./axis/axis";
export {
    ariaHeaderCellSpans,
    ariaRowCount,
    ariaRowDetail,
    ariaRowIndex,
    columnLeft,
    columnPinning,
    createDataGridEngine,
    type DataGridEngine,
    type DataGridEngineOptions,
    type EngineActionKey,
    type EngineActionMap,
    type EngineAdapter,
    type EngineEventKey,
    type EngineEventMap,
    type EngineLayer,
    type EngineQueryKey,
    type EngineQueryMap,
    type GridView,
    type HeaderCellSort,
    type HeaderRowView,
    headerCellBox,
    headerCellSort,
    renderedWidth,
    rowCellsHeight,
    rowDetailBox,
    rowDisplay,
    rowExpanded,
    rowLeft,
    rowSelectable,
    rowSelected,
    rowTop,
    rowWidth,
    TAB_STOP_ATTRIBUTE,
} from "./engine/engine";
export { DEFAULT_DETAIL_HEIGHT, sameRowKeys } from "./model/expansion";
export {
    createDataGridModel,
    type DataGridModel,
    DEFAULT_HEADER_ROW_HEIGHT,
    DEFAULT_ROW_HEIGHT,
} from "./model/model";
export { veto } from "./model/result";
export { sameSortColumns, validSortColumns } from "./model/sort";
export { cellValue, rowAt } from "./model/source";
export type {
    CellPosition,
    CellRenderProps,
    Column,
    ColumnGroup,
    ColumnOrGroup,
    CommandArgs,
    CommandContext,
    CommandError,
    CommandErrorCode,
    CommandEvent,
    CommandFailure,
    CommandListener,
    CommandMap,
    CommandName,
    CommandResult,
    DataGridModelOptions,
    DataGridState,
    DataSetPayload,
    DetailHeight,
    GroupHeaderCellRenderProps,
    HeaderCellLayout,
    HeaderCellRenderProps,
    HeaderLayout,
    Middleware,
    NoPayload,
    PayloadArgs,
    PayloadOf,
    QueryKey,
    QueryMap,
    QuestionKey,
    QuestionMap,
    ResultOf,
    RowKey,
    RowKeyGetter,
    RowSelectable,
    RowSelection,
    RowSource,
    SelectionAnchor,
    SortColumn,
    SortDirection,
} from "./model/types";
export {
    type Direction,
    type HeaderCellSpan,
    sameCell,
} from "./navigation/navigation";
export { DEFAULT_MAX_SCROLL_SIZE } from "./viewport/scaling";
export type { ScrollAlign } from "./viewport/scroll-target";
export {
    type AxisWindow,
    EMPTY_WINDOW,
    type Range,
} from "./viewport/window";
