// @fragiola/data-grid: the framework-free core of the headless data grid.

export {
    type Axis,
    type AxisExtra,
    createAxis,
    type Size,
    withExtraSizes,
} from "./axis/axis";
export {
    ariaHeaderCellSpans,
    ariaRowCount,
    ariaRowDetail,
    ariaRowIndex,
    columnLeft,
    columnPinning,
    createDataGridEngine,
    type DataGridEngine,
    type DataGridEngineOptions,
    type EngineActionKey,
    type EngineActionMap,
    type EngineAdapter,
    type EngineEventKey,
    type EngineEventMap,
    type EngineLayer,
    type EngineQueryKey,
    type EngineQueryMap,
    type GridView,
    type HeaderCellSort,
    type HeaderRowView,
    headerCellBox,
    headerCellSort,
    pinnedInset,
    renderedWidth,
    rowCellsHeight,
    rowDetailBox,
    rowDisplay,
    rowExpanded,
    rowLeft,
    rowSelectable,
    rowSelected,
    rowTop,
    rowWidth,
    TAB_STOP_ATTRIBUTE,
} from "./engine/engine";
export {
    type ColumnLayout,
    columnsError,
    headerCellsIn,
    isColumnGroup,
    layoutColumns,
} from "./header/header";
export { DEFAULT_DETAIL_HEIGHT, sameRowKeys } from "./model/expansion";
export {
    COMMANDS,
    cellValue,
    createDataGridModel,
    type DataGridModel,
    DEFAULT_HEADER_ROW_HEIGHT,
    DEFAULT_ROW_HEIGHT,
    veto,
} from "./model/model";
export { sameSortColumns, validSortColumns } from "./model/sort";
export { rowAt } from "./model/source";
export type {
    CellPosition,
    CellRenderProps,
    Column,
    ColumnGroup,
    ColumnOrGroup,
    CommandArgs,
    CommandContext,
    CommandContextBase,
    CommandError,
    CommandErrorCode,
    CommandEvent,
    CommandListener,
    CommandMap,
    CommandName,
    CommandResult,
    DataGridModelOptions,
    DataGridState,
    DataSetPayload,
    DetailHeight,
    GroupHeaderCellRenderProps,
    HeaderCellLayout,
    HeaderCellRenderProps,
    HeaderLayout,
    Middleware,
    PayloadArgs,
    PayloadOf,
    QueryKey,
    QueryMap,
    QuestionKey,
    QuestionMap,
    ResultOf,
    RowKey,
    RowKeyGetter,
    RowSelectable,
    RowSelection,
    RowSource,
    SelectionAnchor,
    SortColumn,
    SortDirection,
} from "./model/types";
export {
    DIRECTIONS,
    type Direction,
    type GridBounds,
    type HeaderCellSpan,
    nextPosition,
    sameCell,
} from "./navigation/navigation";
export {
    createScrollMapping,
    DEFAULT_MAX_SCROLL_SIZE,
    ScrollAxisState,
    type ScrollMapping,
} from "./viewport/scaling";
export {
    type ScrollAlign,
    scrollTargetFor,
    scrollTargetForSpan,
} from "./viewport/scroll-target";
export {
    type AxisWindow,
    contains,
    EMPTY_RANGE,
    EMPTY_WINDOW,
    type Range,
    sameRange,
    sameWindow,
    visibleRange,
    windowFor,
    withOverscan,
} from "./viewport/window";
