// @fragiola/data-grid: the framework-free core of the headless data grid.

export { type Axis, createAxis, type Size } from "./axis/axis";
export {
    ariaHeaderCellSpans,
    ariaRowCount,
    ariaRowIndex,
    columnLeft,
    createDataGridEngine,
    type DataGridEngine,
    type DataGridEngineOptions,
    type EngineActionKey,
    type EngineActionMap,
    type EngineAdapter,
    type EngineEventKey,
    type EngineEventMap,
    type EngineLayer,
    type EngineQueryKey,
    type EngineQueryMap,
    type GridView,
    type HeaderCellSort,
    type HeaderRowView,
    headerCellBox,
    headerCellSort,
    renderedWidth,
    rowTop,
} from "./engine/engine";
export {
    type ColumnLayout,
    columnsError,
    headerCellsIn,
    isColumnGroup,
    layoutColumns,
} from "./header/header";
export {
    COMMANDS,
    cellValue,
    createDataGridModel,
    type DataGridModel,
    DEFAULT_HEADER_ROW_HEIGHT,
    DEFAULT_ROW_HEIGHT,
    rowAt,
    veto,
} from "./model/model";
export type {
    CellPosition,
    CellRenderProps,
    Column,
    ColumnGroup,
    ColumnOrGroup,
    CommandArgs,
    CommandContext,
    CommandContextBase,
    CommandError,
    CommandErrorCode,
    CommandEvent,
    CommandListener,
    CommandMap,
    CommandName,
    CommandResult,
    DataGridModelOptions,
    DataGridState,
    DataSetPayload,
    GroupHeaderCellRenderProps,
    HeaderCellLayout,
    HeaderCellRenderProps,
    HeaderLayout,
    Middleware,
    PayloadArgs,
    PayloadOf,
    QueryKey,
    QueryMap,
    QuestionKey,
    QuestionMap,
    ResultOf,
    RowKeyGetter,
    RowSource,
    SortColumn,
    SortDirection,
} from "./model/types";
export {
    DIRECTIONS,
    type Direction,
    type GridBounds,
    type HeaderCellSpan,
    nextPosition,
    sameCell,
} from "./navigation/navigation";
export {
    createScrollMapping,
    DEFAULT_MAX_SCROLL_SIZE,
    ScrollAxisState,
    type ScrollMapping,
} from "./viewport/scaling";
export { type ScrollAlign, scrollTargetFor } from "./viewport/scroll-target";
export {
    type AxisWindow,
    contains,
    EMPTY_RANGE,
    EMPTY_WINDOW,
    type Range,
    sameRange,
    sameWindow,
    visibleRange,
    windowFor,
    withOverscan,
} from "./viewport/window";
